---
title: "Data"
author: "Marcelo Hurtado"
date: "2022-09-21"
output: html_document
---

Load packages and functions
```{r}
source(paste0(getwd(),"/environment_set.R"))
libraries_set()
```

Lung Predict data
```{r}
#Import Counts
Counts <- as.matrix(read.table(paste0(getwd(),"/RawFiles/LP_STAR_RSEM_matrix_LEILA.txt"), header=T, row.names = 1))
colnames(Counts) = gsub("X.home.leilak.......media.leilak.LaCie.LungPredict.Adenocarcinoma.RSEM.RNAseq_quals.", "", colnames(Counts))
colnames(Counts) = gsub(".genes.results", "", colnames(Counts))
Counts <- as.data.frame(Counts)
Counts$Genes = rownames(Counts)

##Import Clinical data
clinical.data <- data.frame(read.csv(paste0(getwd(),"/RawFiles/ColumnData_LungPredict.csv"), row.names = 1))
clinical.data$Smoking_Status[which(clinical.data$Smoking_Status == 'Old')] <- 'Y' 
clinical.data$Smoking_Status[which(clinical.data$Smoking_Status == 'Yes')] <- 'Y'
clinical.data$Smoking_Status[which(clinical.data$Smoking_Status == 'No')] <- 'N'

##Match samples in clinical.data and counts
Counts = as.data.frame(Counts[, intersect(colnames(Counts), rownames(clinical.data))])
Counts <- Counts[,match(rownames(clinical.data), colnames(Counts))]

#Look for outliers
SampleDist = dist(t(Counts))
SampleDistMatrix = as.matrix(SampleDist)
colors = colorRampPalette( rev(brewer.pal(9, "Purples")) )(255)
png(paste0(getwd(),"/Figures/DistanceMatrix/SampleDistanceMatrix_Counts_LungPredict.png"), width = 5000, height = 4500, res = 350)
pheatmap(SampleDistMatrix, clustering_distance_rows = SampleDist, clustering_distance_cols = SampleDist, col=colors)
dev.off()

#Import deconvolution
deconv <- as.matrix(read.delim(paste0(getwd(),"/RawFiles/Deconvolution/Deconvolutions_LungPredict.txt"), row.names = 1))

#Remove MCP method results
deconv <- deconv[,-grep("MCP", colnames(deconv))]

#Look for outliers
SampleDist = dist(deconv)
SampleDistMatrix = as.matrix(SampleDist)
colors = colorRampPalette( rev(brewer.pal(9, "Purples")) )(255)
png(paste0(getwd(),"/Figures/DistanceMatrix/SampleDistanceMatrix_Deconvolution_LungPredict.png"), width = 5000, height = 4500, res = 350)
pheatmap(SampleDistMatrix, clustering_distance_rows = SampleDist, clustering_distance_cols = SampleDist, col=colors)
dev.off()

#Remove outliers
deconv <- deconv[-which(rownames(deconv)=="LP.01.69"),] 

#Match samples in all files
Counts = Counts[, intersect(colnames(Counts), rownames(deconv))]
clinical.data = clinical.data[intersect(rownames(clinical.data),colnames(Counts)),]

#Check features numbers
table(clinical.data$Stages_simplified)
table(clinical.data$Gender)
table(clinical.data$Metastatic)
table(clinical.data$Smoking_Status)
table(clinical.data$Age_Bracket)
table(clinical.data$KRAS_mut)
table(clinical.data$EGFR_mut)
table(clinical.data$STK11_mut)

##Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_LungPredict.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_LungPredict.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_LungPredict.csv"), row.names = T)
```

ImmunoPredict data
```{r}
#Import Counts
Counts <- as.matrix(read.table(paste0(getwd(),"/RawFiles/IP_STAR_RSEM_matrix_LEILA.txt"), header = T, row.names = 1))
colnames(Counts) = gsub("X.home.leilak.......media.leilak.LaCie.ImmunePredict.RSEM.RNAseq_quals.", "", colnames(Counts))
colnames(Counts) = gsub(".genes.results", "", colnames(Counts))
Counts <- as.data.frame(Counts)

##Import Clinical data
clinical.data <- data.frame(read.csv(paste0(getwd(),"/RawFiles/clinical_dataIP.csv"), row.names = 1))

##Match samples in clinical.data and counts
Counts = as.data.frame(Counts[,intersect(colnames(Counts), rownames(clinical.data))])
Counts <- Counts[,match(rownames(clinical.data), colnames(Counts))]

#Look for outliers
SampleDist = dist(t(Counts))
SampleDistMatrix = as.matrix(SampleDist)
colors = colorRampPalette( rev(brewer.pal(9, "Purples")) )(255)
png(paste0(getwd(),"/Figures/DistanceMatrix/SampleDistanceMatrix_Counts_ImmunoPredict.png"), width = 5000, height = 4500, res = 350)
pheatmap(SampleDistMatrix, clustering_distance_rows = SampleDist, clustering_distance_cols = SampleDist, col=colors)
dev.off()

#Remove outliers
Counts <- Counts[,-which(colnames(Counts)=="IP.60")] 
clinical.data = clinical.data[intersect(rownames(clinical.data), colnames(Counts)),]

#Import deconvolution
deconv <- as.matrix(read.delim(paste0(getwd(),"/RawFiles/Deconvolution/Deconvolutions_ImmunoPredict.txt"), row.names = 1))
deconv = deconv[intersect(rownames(deconv), rownames(clinical.data)),]

#Remove MCP method results
deconv <- deconv[,-grep("MCP", colnames(deconv))]

#Look for outliers
SampleDist = dist(deconv)
SampleDistMatrix = as.matrix(SampleDist)
colors = colorRampPalette( rev(brewer.pal(9, "Purples")) )(255)
png(paste0(getwd(),"/Figures/DistanceMatrix/SampleDistanceMatrix_Deconvolution_ImmunoPredict.png"), width = 5000, height = 4500, res = 350)
pheatmap(SampleDistMatrix, clustering_distance_rows = SampleDist, clustering_distance_cols = SampleDist, col=colors)
dev.off()

#Match samples in all files
Counts = Counts[, intersect(colnames(Counts), rownames(deconv))]
clinical.data = clinical.data[intersect(rownames(clinical.data),colnames(Counts)),]

#Check features numbers
table(clinical.data$Stages_simplified)
table(clinical.data$Gender)
table(clinical.data$Smoking_Status)
table(clinical.data$Age_Bracket)
table(clinical.data$KRAS_mut)

##Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_ImmunoPredict.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_ImmunoPredict.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_ImmunoPredict.csv"), row.names = T)
```

Vanderbilt data
```{r}
##Import Counts
Counts <- as.matrix(read.csv(paste0(getwd(),"/RawFiles/CountData_Vanderbilt.csv"), row.names = 1))
Counts <- as.matrix(Counts)
rownames(Counts) = gsub("\\..*", "", rownames(Counts))
entrz <- AnnotationDbi::select(org.Hs.eg.db, keys = rownames(Counts), columns = "SYMBOL", keytype = "ENSEMBL")
Counts <- as.data.frame(Counts)
Counts$ENSEMBL <- rownames(Counts)
Counts <- Counts %>%
  inner_join(., entrz, by="ENSEMBL") %>%
  dplyr::filter(!is.na(SYMBOL))
gene_means <- rowMeans(Counts %>% dplyr::select(-ENSEMBL, -SYMBOL))
Counts <- Counts %>%
  dplyr::mutate(gene_means) %>% 
  dplyr::select(ENSEMBL, SYMBOL, gene_means, dplyr::everything()) 
Counts <- Counts %>%
  dplyr::arrange(dplyr::desc(gene_means)) %>% 
  dplyr::distinct(SYMBOL, .keep_all = TRUE)  
Counts <- Counts %>%
  dplyr::select(-ENSEMBL, -gene_means) %>%   
  tibble::column_to_rownames("SYMBOL") %>%   
  as.matrix() 

##Import Clinical data
clinical.data <- data.frame(read.csv(paste0(getwd(),"/RawFiles/ColumnData_Vanderbilt.csv"), row.names = 1))
clinical.data <- clinical.data[,c(5,6,9,11,13)]
clinical.data$Smoking_Status[which(clinical.data$Smoking_Status == 'Ex')] <- 'Y' 
clinical.data$Smoking_Status[which(clinical.data$Smoking_Status == 'Current')] <- 'Y'
clinical.data$Smoking_Status[which(clinical.data$Smoking_Status == 'Never')] <- 'N'
clinical.data$Gender[which(clinical.data$Gender == 'Male')] <- 'M'
clinical.data$Gender[which(clinical.data$Gender == 'Female')] <- 'F' 
clinical.data$Stages_simplified[which(clinical.data$Stages_simplified == 'Stage_I')] <- 'I'
clinical.data$Stages_simplified[which(clinical.data$Stages_simplified == 'Stage_II')] <- 'II' 
clinical.data$Stages_simplified[which(clinical.data$Stages_simplified == 'Stage_III')] <- 'III'
clinical.data <- clinical.data[-which(clinical.data$Stages_simplified=='Stage_0'),]

##Match samples in clinical.data and counts
Counts <- Counts[,intersect(rownames(clinical.data), colnames(Counts))]
clinical.data <- clinical.data[match(colnames(Counts), rownames(clinical.data)),]

#Look for outliers
SampleDist = dist(t(Counts))
SampleDistMatrix = as.matrix(SampleDist)
colors = colorRampPalette( rev(brewer.pal(9, "Purples")) )(255)
png(paste0(getwd(),"/Figures/DistanceMatrix/SampleDistanceMatrix_Counts_Vanderbilt.png"), width = 5000, height = 4500, res = 350)
pheatmap(SampleDistMatrix, clustering_distance_rows = SampleDist, clustering_distance_cols = SampleDist, col=colors)
dev.off()

#Remove outliers
Counts <- Counts[,-which(colnames(Counts)=="R3388_YZ_22"|colnames(Counts)=="R3388_YZ_18"|colnames(Counts)=="R3388_YZ_53"|colnames(Counts)=="R3388_YZ_59")] 
clinical.data = clinical.data[intersect(rownames(clinical.data), colnames(Counts)),]

#Import deconvolution
deconv <- as.matrix(read.delim(paste0(getwd(),"/RawFiles/Deconvolution/Deconvolutions_Vanderbilt.txt"), row.names = 1))
deconv = deconv[intersect(rownames(clinical.data), rownames(deconv)),]

#Remove MCP method results
deconv <- deconv[,-grep("MCP", colnames(deconv))]

#Look for outliers
SampleDist = dist(deconv)
SampleDistMatrix = as.matrix(SampleDist)
colors = colorRampPalette( rev(brewer.pal(9, "Purples")) )(255)
png(paste0(getwd(),"/Figures/DistanceMatrix/SampleDistanceMatrix_Deconvolution_Vanderbilt.png"), width = 5000, height = 4500, res = 350)
pheatmap(SampleDistMatrix, clustering_distance_rows = SampleDist, clustering_distance_cols = SampleDist, col=colors)
dev.off()

#Match samples in all files
Counts = Counts[, intersect(colnames(Counts), rownames(deconv))]
clinical.data = clinical.data[intersect(rownames(clinical.data),colnames(Counts)),]

#Check features numbers
table(clinical.data$Stages_simplified)
table(clinical.data$Gender)
table(clinical.data$Smoking_Status)
table(clinical.data$Age_Bracket)

##Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_Vanderbilt.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_Vanderbilt.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_Vanderbilt.csv"), row.names = T)
```

LungPredict and Vanderbilt
```{r}
#Import counts
Counts1 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_LungPredict.csv"), row.names = 1)
Counts2 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_Vanderbilt.csv"), row.names = 1)

m2 <- do.call(rbind, strsplit(rownames(Counts1), split="_", fixed = TRUE))
Counts1 <- as.matrix(Counts1)
rownames(Counts1) = m2[,2]

Counts1 = data.frame(Counts1)
Counts2 = data.frame(Counts2)
Counts1$Genes = rownames(Counts1)
Counts2$Genes = rownames(Counts2)

Counts1 <- Counts1 %>%
  inner_join(., Counts2, by= "Genes") 

rownames(Counts1) <- Counts1$Genes

Counts1$Genes = NULL
Counts2$Genes = NULL

#Import clinical data
clinical.data1 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_LungPredict.csv"), row.names = 1)
clinical.data2 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Vanderbilt.csv"), row.names = 1)

clinical.data1 = clinical.data1[-which(clinical.data1$Stages_simplified=="IV"),]
clinical.data1$EGFR_mut = NULL
clinical.data1$KRAS_mut = NULL
clinical.data1$STK11_mut = NULL
clinical.data1$Metastatic = NULL

clinical.data2$Batch[which(clinical.data2$Batch == '1')] <- '5' 
clinical.data2$Batch[which(clinical.data2$Batch == '2')] <- '6' 
clinical.data = rbind(clinical.data1, clinical.data2)

#Import deconvolution
deconv1 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_LungPredict.csv"), row.names = 1)
deconv2 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_Vanderbilt.csv"), row.names = 1)

deconv = rbind(deconv1, deconv2)

Counts = Counts1[,colnames(Counts1)%in%rownames(clinical.data)]
deconv = deconv[rownames(deconv)%in%rownames(clinical.data),]

#Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_LPVan.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_LPVan.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_LPVan.csv"), row.names = T)
```

Immunopredict and Vanderbilt data
```{r}
#Import counts
Counts1 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_Vanderbilt.csv"), row.names = 1)
Counts2 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_ImmunoPredict.csv"), row.names = 1)

#Import clinical data
clinical.data1 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Vanderbilt.csv"), row.names = 1)
clinical.data2 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_ImmunoPredict.csv"), row.names = 1)

#Import deconvolution
deconv1 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_Vanderbilt.csv"), row.names = 1)
deconv2 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_ImmunoPredict.csv"), row.names = 1)

#Join counts
m2 <- do.call(rbind, strsplit(rownames(Counts2), split="_", fixed = TRUE))
Counts2 <- as.matrix(Counts2)
rownames(Counts2) = m2[,2]

Counts1 = data.frame(Counts1)
Counts2 = data.frame(Counts2)
Counts1$Genes = rownames(Counts1)
Counts2$Genes = rownames(Counts2)

Counts1 <- Counts1 %>%
  inner_join(., Counts2, by= "Genes") 

rownames(Counts1) <- Counts1$Genes

Counts1$Genes = NULL
Counts2$Genes = NULL

#Join clinical data
clinical.data2$KRAS_mut = NULL
clinical.data2$Batch[which(clinical.data2$Batch == '5')] <- '3' 
clinical.data <- rbind(clinical.data1, clinical.data2)

#Join deconvolution
deconv = rbind(deconv1, deconv2)

#Save data files
write.csv(Counts1, paste0(getwd(),"/Input/Counts/Counts_VanIP.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_VanIP.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_VanIP.csv"), row.names = T)
```

Response dataset
```{r}
#Import counts
Counts1 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_LungPredict.csv"), row.names = 1)
Counts2 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_ImmunoPredict.csv"), row.names = 1)

#Import clinical data
clinical.data1 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_LungPredict.csv"), row.names = 1)
clinical.data2 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_ImmunoPredict.csv"), row.names = 1)

#Import deconvolution
deconv1 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_LungPredict.csv"), row.names = 1)
deconv2 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_ImmunoPredict.csv"), row.names = 1)

#Join datasets
Counts = cbind(Counts1, Counts2)
clinical.data = rbind(clinical.data1[,intersect(colnames(clinical.data1), colnames(clinical.data2))], clinical.data2)
deconv = rbind(deconv1, deconv2)

#Import response information
response <- read.csv(paste0(getwd(),"/RawFiles/ColumnData_Response.csv"), row.names=1)

#Match samples with response
Counts = Counts[,colnames(Counts) %in% rownames(response)]
clinical.data = clinical.data[rownames(clinical.data)%in%rownames(response),]
deconv = deconv[rownames(deconv)%in%rownames(response),]

#Add information 
clinical.data$response = response$Response

#Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_Response.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_Response.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_Response.csv"), row.names = T)
```

KRAS dataset
```{r}
#Import counts
Counts1 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_LungPredict.csv"), row.names = 1)
Counts2 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_ImmunoPredict.csv"), row.names = 1)
Counts3 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_Vanderbilt.csv"), row.names = 1)

#Import clinical data
clinical.data1 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_LungPredict.csv"), row.names = 1)
clinical.data2 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_ImmunoPredict.csv"), row.names = 1)
clinical.data3 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Vanderbilt.csv"), row.names = 1)

#Import deconvolution
deconv1 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_LungPredict.csv"), row.names = 1)
deconv2 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_ImmunoPredict.csv"), row.names = 1)
deconv3 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_Vanderbilt.csv"), row.names = 1)

#Join counts
Counts = cbind(Counts1, Counts2)
m2 <- do.call(rbind, strsplit(rownames(Counts), split="_", fixed = TRUE))
Counts <- as.matrix(Counts)
rownames(Counts) = m2[,2]

Counts = data.frame(Counts)
Counts3 = data.frame(Counts3)
Counts$Genes = rownames(Counts)
Counts3$Genes = rownames(Counts3)

Counts <- Counts %>%
  inner_join(., Counts3, by= "Genes") 

rownames(Counts) <- Counts$Genes

Counts$Genes = NULL

#Join clinical data
clinical.data = rbind(clinical.data1[,colnames(clinical.data1)%in%colnames(clinical.data3)], clinical.data2[,colnames(clinical.data2)%in%colnames(clinical.data3)], clinical.data3)

#Join deconvolution
deconv = rbind(deconv1, deconv2, deconv3)

#Import KRAS information
KRAS <- read.csv(paste0(getwd(),"/RawFiles/ColumnData_KRAS.csv"), row.names=1)

#Match samples with response
Counts = Counts[,colnames(Counts) %in% rownames(KRAS)]
clinical.data = clinical.data[rownames(clinical.data)%in%rownames(KRAS),]
deconv = deconv[rownames(deconv)%in%rownames(KRAS),]

KRAS = KRAS[rownames(KRAS) %in% rownames(clinical.data),]

#Add information 
clinical.data = cbind(clinical.data, KRAS[,-which(colnames(KRAS)%in%colnames(clinical.data))])

#Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_KRAS.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_KRAS.csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_KRAS.csv"), row.names = T)
```

Melanoma datasets
```{r}
dataset = "Riaz" 
dataset = "Liu"

deconv <- as.matrix(read.csv(paste0(getwd(),"/RawFiles/Deconvolution/Deconvolutions_", dataset, ".txt"), row.names=1, sep=""))
clinical.data <- data.frame(readRDS(paste0(getwd(),"/Input/Matthieu/", dataset, "/processed/dds.RDS"), refhook = NULL)@colData)

immunoscores <- read.csv(paste0(getwd(),"/Input/Matthieu/", dataset, "/processed/immune_scores.txt"), row.names=1, sep="")
TFs <- read.csv(paste0(getwd(),"/Input/Matthieu/", dataset, "/processed/tf_activities.txt"), row.names=1, sep="")

clinical.data = clinical.data[clinical.data$Time=="Pre",]
deconv = deconv[rownames(deconv)%in%rownames(clinical.data),]
immunoscores = immunoscores[immunoscores$condition%in%rownames(clinical.data),]
TFs = TFs[,colnames(TFs)%in%rownames(clinical.data)]

#Save data files
write.csv(immunoscores, paste0(getwd(),"/Output/Immunoscores/ImmuneScores_", dataset, ".csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_", dataset, ".csv"), row.names = T)
write.csv(TFs, paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_", dataset, ".csv"), row.names = T)

#Join datasets
dataset = "Melanoma"

#Import deconvolution
deconv1 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_Riaz.csv"), row.names = 1)
deconv2 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_Liu.csv"), row.names = 1)
#deconv3 <- read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_Gide.csv"), row.names = 1)

#Import TFS
TFs1 <- read.csv(paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_Riaz.csv"), row.names = 1)
TFs2 <- read.csv(paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_Liu.csv"), row.names = 1)
#TFs3 <- read.csv(paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_Gide.csv"), row.names = 1)

#Import immunoscores
immunoscores1 <- read.csv(paste0(getwd(),"/Output/Immunoscores/ImmuneScores_Riaz.csv"), row.names = 1)
immunoscores2 <- read.csv(paste0(getwd(),"/Output/Immunoscores/ImmuneScores_Liu.csv"), row.names = 1)
#immunoscores3 <- read.csv(paste0(getwd(),"/Output/Immunoscores/ImmuneScores_Gide.csv"), row.names = 1)

#Import clinical data
clinical.data1 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Riaz.csv"), row.names = 1)
clinical.data2 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Liu.csv"), row.names = 1)
#clinical.data3 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Gide.csv"), row.names = 1)
clinical.data2$Cohort = "Liu"
  
deconv = rbind(deconv1, deconv2)
TFs = cbind(TFs1, TFs2)
immunoscores = rbind(immunoscores1, immunoscores2)
clinical.data = rbind(clinical.data1, clinical.data2)

#Save data files
write.csv(immunoscores, paste0(getwd(),"/Output/Immunoscores/ImmuneScores_", dataset, ".csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = T)
write.csv(deconv, paste0(getwd(),"/Input/Deconvolution/Deconvolution_", dataset, ".csv"), row.names = T)
write.csv(TFs, paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_", dataset, ".csv"), row.names = T)
```


