---
title: "Mounim"
author: "Marcelo Hurtado"
date: "2023-05-23"
output: html_document
---

Datasets
```{r}
dataset = "LPVan"
```

Input files
```{r}
#Import counts
Counts1 <- read.csv(paste0(getwd(),"/Input/Counts/Counts_LungPredict.csv"), row.names = 1)
clinical.data1 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_LungPredict.csv"), row.names = 1)
m2 <- do.call(rbind, strsplit(rownames(Counts1), split="_", fixed = TRUE))
Counts1 <- as.matrix(Counts1)
rownames(Counts1) = m2[,1]
Counts1 = data.frame(Counts1)

##Import Counts
Counts2 <- as.matrix(read.csv(paste0(getwd(),"/RawFiles/CountData_Vanderbilt.csv"), row.names = 1))
clinical.data2 <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Vanderbilt.csv"), row.names = 1)
Counts2 <- as.matrix(Counts2)
rownames(Counts2) = gsub("\\..*", "", rownames(Counts2))
Counts2 = data.frame(Counts2)

Counts1$Ensembl = rownames(Counts1)
Counts2$Ensembl = rownames(Counts2)

Counts <- Counts1 %>%
  inner_join(., Counts2, by= "Ensembl") 

rownames(Counts) <- Counts$Ensembl

```

Only early stage samples (I, II)
```{r}
clinical.data1$EGFR_mut = NULL
clinical.data1$KRAS_mut = NULL
clinical.data1$STK11_mut = NULL
clinical.data1$Metastatic = NULL

clinical.data2$Batch[which(clinical.data2$Batch == '1')] <- '5' 
clinical.data2$Batch[which(clinical.data2$Batch == '2')] <- '6' 

clinical.data = rbind(clinical.data1, clinical.data2)
clinical.data = clinical.data[-which(clinical.data$Stages_simplified%in%c("III","IV")),]

Counts = Counts[,colnames(Counts)%in%rownames(clinical.data)]
```

TPM normalization
```{r}
Counts = TPM_normalization(Counts)
```

Remove batch effect
```{r}

p <- pca(Counts, clinical.data, removeVar = 0.1)
  
peigencor  <- eigencorplot(p,
                             components = getComponents(p, 1:6),
                             metavars = colnames(clinical.data),
                             col = c('white', 'cornsilk1', 'gold', 'forestgreen', 'darkgreen'),
                             cexCorval = 1.2,
                             fontCorval = 2,
                             posLab = 'all',
                             rotLabX = 45,
                             scale = TRUE,
                             main = bquote(Principal ~ component ~ Pearson ~ r^2 ~ clinical ~ correlates),
                             plotRsquared = TRUE,
                             corFUN = 'pearson',
                             corUSE = 'pairwise.complete.obs',
                             corMultipleTestCorrection = 'BH',
                             signifSymbols = c('****', '***', '**', '*', ''),
                             signifCutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1))
  
png(paste0(getwd(),"/Figures/PCA/peigencor_", paste0("Counts_TPM_BE_",dataset), ".png"), width = 2500, height = 1500, res = 150)
print(peigencor)
dev.off()

Counts <- limma::removeBatchEffect(Counts, batch=clinical.data$Batch) #Samples as columns

p <- pca(Counts, clinical.data, removeVar = 0.1)
  
peigencor  <- eigencorplot(p,
                             components = getComponents(p, 1:6),
                             metavars = colnames(clinical.data),
                             col = c('white', 'cornsilk1', 'gold', 'forestgreen', 'darkgreen'),
                             cexCorval = 1.2,
                             fontCorval = 2,
                             posLab = 'all',
                             rotLabX = 45,
                             scale = TRUE,
                             main = bquote(Principal ~ component ~ Pearson ~ r^2 ~ clinical ~ correlates),
                             plotRsquared = TRUE,
                             corFUN = 'pearson',
                             corUSE = 'pairwise.complete.obs',
                             corMultipleTestCorrection = 'BH',
                             signifSymbols = c('****', '***', '**', '*', ''),
                             signifCutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1))
  
png(paste0(getwd(),"/Figures/PCA/peigencor_", paste0("Counts_TPM_AfterBE_",dataset), ".png"), width = 2500, height = 1500, res = 150)
print(peigencor)
dev.off()
```

```{r}
#Save data files
write.csv(Counts, paste0(getwd(),"/Input/Counts/Counts_LPVan_TPM.csv"), row.names = T)
write.csv(clinical.data, paste0(getwd(),"/Input/ClinicalData/ClinicalData_LPVan.csv"), row.names = T)
```
```{r}
Counts_LPVan <- read.csv("~/LungPredict/Input/Counts/Counts_LPVan_TPM.csv", row.names=1)
```

```{r}
entrz = gconvert(row.names(Counts_LPVan), organism = "hsapiens", target = "ENTREZGENE_ACC", filter_na = F, mthreshold = 1)

which(duplicated(Counts_LPVan$Symbol))
entrz = entrz[,c(2,5)]
colnames(entrz)[c(1,2)] = c("ENSEMBL","SYMBOL") 
Counts_LPVan$ENSEMBL <- rownames(Counts_LPVan)
Counts_LPVan <- Counts_LPVan %>%
  inner_join(., entrz, by="ENSEMBL") %>%
  dplyr::filter(!is.na(SYMBOL))
gene_means <- rowMeans(Counts_LPVan %>% dplyr::select(-ENSEMBL, -SYMBOL))
Counts_LPVan <- Counts_LPVan %>%
  dplyr::mutate(gene_means) %>% 
  dplyr::select(ENSEMBL, SYMBOL, gene_means, dplyr::everything()) 
Counts_LPVan <- Counts_LPVan %>%
  dplyr::arrange(dplyr::desc(gene_means)) %>% 
  dplyr::distinct(SYMBOL, .keep_all = TRUE)  
Counts_LPVan <- Counts_LPVan %>%
  dplyr::select(-ENSEMBL, -gene_means) %>%   
  tibble::column_to_rownames("SYMBOL") %>%   
  as.matrix() 

head(Counts_LPVan)
write.csv(Counts_LPVan, paste0(getwd(),"/Input/Counts/Counts_LPVan_TPM.csv"), row.names = T)

```

