---
title: "Features analysis"
author: "Marcelo Hurtado"
date: "2023-01-13"
output: html_document
---

Load packages and functions
```{r}
source(paste0(getwd(),"/environment_set.R"))
source(paste0(getwd(),"/Immunoscores.R"))
libraries_set()
```

Datasets
```{r}
dataset = "LungPredict"
dataset = "Vanderbilt"
dataset = "Response"
dataset = "LPVan_Early"
```

Input files
```{r}
Counts_normalized <- as.matrix(read.csv(paste0(getwd(),"/Output/Counts_normalized_vsd_", dataset, ".csv"), row.names = 1))
clinical.data <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = 1)
dds = readRDS(paste0(getwd(), "/Output/DESeqObject_", dataset))
```

Differential expression
```{r}
#Lung Predict
diff_expression(dds, "Stages_simplified", "I", "IV", "LungPredict_Stages_IvsIV")
diff_expression(dds, "KRAS_mut", "Y", "N", "LungPredict_KRAS_YvsN")
diff_expression(dds, "STK11_mut", "Y", "N", "LungPredict_STK11_YvsN")
diff_expression(dds, "EGFR_mut", "Y", "N", "LungPredict_EGFR_YvsN")
diff_expression(dds, "VISTArank", "HIGH", "LOW", "LungPredict_VISTA_HIGHvsLOW")
```

Converting gene ID to SYMBOL (if needed)
```{r}
m2 <- do.call(rbind, strsplit(rownames(Counts_normalized), split="_", fixed = TRUE))
Counts_normalized = as.matrix(Counts_normalized)
rownames(Counts_normalized) = m2[,2]
```

Pathway analysis 
```{r}
pathways = compute_pathways_scores(Counts_normalized, dataset)
```

TF analysis
```{r}
TFs = compute_TFs_scores(Counts_normalized, dataset)
```

Compute immunoscores
```{r}
list_gold_standards=c("CYT","Roh_IS","Davoli_IS", "IFNy","Ayers_expIS","Tcell_inflamed")
gold.standards <- compute_gold_standards(RNA.tpm = data.frame(Counts_normalized), list_gold_standards, dataset)
```


