---
title: "ResponseAnalysis"
author: "Marcelo Hurtado"
date: "2023-06-14"
output: html_document
---

```{r}
source(paste0(getwd(),"/environment_set.R"))
libraries_set()
```

```{r}
dataset = "Response"
```

```{r}
deconv <- as.matrix(read.csv(paste0(getwd(),"/Input/Deconvolution/Deconvolution_", dataset, ".csv"), row.names = 1))
clinical.data <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = 1)
deconv = deconv[rownames(deconv)%in%rownames(clinical.data),]
```

```{r}
#Removing CD226
deconv <- deconv[,-grep("CD226", colnames(deconv))]
#Remove columns with low variance (no much change across samples)
deconv = data.frame(deconv[,-which(colVars(deconv)<=summary(colVars(deconv))[2])])
#Remove columns with more than 80% of zeros
i <- colSums(deconv == 0, na.rm=TRUE) < round(0.7*nrow(deconv))
deconv <- data.frame(deconv[, i, drop=FALSE])
```

```{r}
compute_cell.types = function(data){
  #columns:features and rows:samples
  ################################# B cells
  Bcells <- data[,grep("B", colnames(data))]
  if(length(grep("M2", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("M2", colnames(Bcells))]}else{Bcells <- Bcells}
  if(length(grep("ancer", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("ancer", colnames(Bcells))]}else{Bcells <- Bcells}
  if(length(grep("asophils", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("asophils", colnames(Bcells))]}else{Bcells <- Bcells}
  if(length(grep("CD4", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("CD4", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("Mono", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("Mono", colnames(Bcells))]}else{Bcells <- Bcells}
  if(length(grep("Treg", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("Treg", colnames(Bcells))]}else{Bcells <- Bcells}
  if(length(grep("Neu", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("Neu", colnames(Bcells))]}else{Bcells <- Bcells}
  if(length(grep("M1", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("M1", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("CD8", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("CD8", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("M0", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("M0", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("NK", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("NK", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("ndothelial", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("ndothelial", colnames(Bcells))]}else{Bcells <- Bcells}      
  if(length(grep("CAF", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("CAF", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("acrophage", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("acrophage", colnames(Bcells))]}else{Bcells <- Bcells}        
  if(length(grep("endritic", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("endritic", colnames(Bcells))]}else{Bcells <- Bcells}      
  if(length(grep("alignant", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("alignant", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("Mast", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("Mast", colnames(Bcells))]}else{Bcells <- Bcells}    
  if(length(grep("yocyte", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("yocyte", colnames(Bcells))]}else{Bcells <- Bcells}  
  if(length(grep("ibroblast", colnames(Bcells)))>0){Bcells <- Bcells[,-grep("ibroblast", colnames(Bcells))]}else{Bcells <- Bcells} 
  B = Bcells
  
  Macrophages = data[,grep("acrophages", colnames(data))]
  M0 = data[,grep("M0", colnames(data))]
  M1 = data[,grep("M1", colnames(data))]
  M2 <- data[,grep("M2", colnames(data))]
  if(length(grep("LM22", colnames(M2)))>0){M2 <- M2[,-grep("LM22", colnames(M2))]}else{M2 <- M2} 
  test = data[,grep("LM22", colnames(data))]
  test = test[,grep("Macrophages.M2", colnames(test))]
  M2 = cbind(M2, test)
  Macrophages = Macrophages[,-which(colnames(Macrophages)%in%c(colnames(M0), colnames(M1), colnames(M2)))]
  
  Monocytes = data[,grep("Mono", colnames(data))]
  Neutrophils <- data[,grep("Neu", colnames(data))]
  
  NK = data[,grep("NK", colnames(data))]
  NK.activated <- grep("activated", colnames(NK), value = TRUE)
  NK.activated <- NK[, NK.activated, drop = FALSE]
  NK.resting = grep("resting", colnames(NK))
  NK.resting <- NK[, NK.resting, drop = FALSE]
  NKT = grep("NKT", colnames(NK))
  NKT <- NK[, NKT, drop = FALSE]
  NK = NK[,-which(colnames(NK)%in%c(colnames(NK.activated), colnames(NK.resting), colnames(NKT)))]  
  
  ################################# CD4 cells
  CD4 <- data[,grep("CD4", colnames(data))]
  CD4.activated = grep("activated", colnames(CD4))
  CD4.activated = CD4[, CD4.activated, drop = FALSE]
  CD4.resting = grep("resting", colnames(CD4))
  CD4.resting = CD4[, CD4.resting, drop = FALSE]
  CD4.naive = grep("naive", colnames(CD4))
  CD4.naive = CD4[, CD4.naive, drop = FALSE]
  CD4.non.regulatory = grep("regulatory", colnames(CD4))
  CD4.non.regulatory = CD4[, CD4.non.regulatory, drop = FALSE]
  CD4 = CD4[,-which(colnames(CD4)%in%c(colnames(CD4.activated), colnames(CD4.resting), colnames(CD4.naive), colnames(CD4.non.regulatory)))]  
  
  ################################# CD8 cells
  CD8 <- data[,grep("CD8", colnames(data))]
  Tregs = data[,grep("regs", colnames(data))]
  Dendritic = data[,grep("endritic", colnames(data))]
  Dendritic.activated = grep("activated", colnames(Dendritic))
  Dendritic.activated = Dendritic[, Dendritic.activated, drop = FALSE]
  Dendritic.resting = grep("resting", colnames(Dendritic))
  Dendritic.resting = Dendritic[, Dendritic.resting, drop = FALSE]
  Dendritic = Dendritic[,-which(colnames(Dendritic)%in%c(colnames(Dendritic.activated), colnames(Dendritic.resting)))]
  
  Cancer = data[,grep("ancer", colnames(data))]
  
  Endothelial = grep("dothelial", colnames(data))
  Endothelial = data[, Endothelial, drop = FALSE]
  
  CAF = data[,grep("CAF", colnames(data))]
  
  cell_types = list(B, Macrophages, M0, M1, M2, Monocytes, Neutrophils, NK, NK.activated, NK.resting, NKT, CD4, CD4.activated, CD4.resting, CD8, Tregs, Dendritic, Dendritic.activated,
                    Dendritic.resting, Cancer, Endothelial, CAF)
  names(cell_types) = c("B", "MACROPHAGES", "M0", "M1", "M2", "MONOCYTES", "NEUTROPHILS", "NK", "NK.ACTIVATED", "NK.RESTING", "NKT", "CD4", "CD4.ACTIVATED", "CD4.RESTING", 
                        "CD8", "TREGS", "DENDRITIC", "DENDRITIC.ACTIVATED", "DENDRITIC.RESTING", "CANCER", "ENDOTHELIAL", "CAF")
  
  return(cell_types)
  
}
cells = compute_cell.types(data.frame(deconv))
```

```{r}
#Pairwise correlation
removeCorrelatedFeatures <- function(data, threshold = 0.95) {
  # Compute correlation matrix
  corr_matrix <- cor(data)
  # Find highly correlated features
  high_corr_pairs <- findCorrelation(corr_matrix, cutoff = threshold, names = TRUE)
  # Select only the variables to keep
  new_data <- data.frame(data[, -which(colnames(data)%in%high_corr_pairs)])
  if(ncol(new_data)==1){
    colnames(new_data)[1] = colnames(data)[1]
  }
  return(new_data)
}
for (i in 1:length(cells)) {
  data = cells[[i]]
  if(ncol(data)>1){
    data = removeCorrelatedFeatures(data)
    cells[[i]] = data
  }
}
```


```{r}
remove_subgroups = function(groups){
  lis = c()
  for (pos in 1:length(groups)){
    x = c()
    if(length(groups[[pos]])!=0){
      for (i in 1:length(groups[[pos]])) {
        for (j in 1:length(groups[[pos]][[i]])) {
          x =  c(x,str_split(groups[[pos]][[i]], "_")[[j]][[1]])
        }
        if(length(unique(x)) == 1){lis = c(lis, names(groups[[pos]])[[i]])}
      }

    }else{
      pos = pos+1
    }
  }
  
  return(lis)
}
```

```{r}
compute_subgroups = function(data, name, thres_similarity = 0.05, thres_corr = 0.7, thres_change = 0.01){
  # data  = data.frame(cells[[2]])
  # cell = names(cells)[2]
  data = data.frame(data)
  if (ncol(data) < 2) {
    warning("Data must have at least two columns for subgrouping.")
    cell_subgroups = list()
    subgroup = list()
    lis = c()
    return(list(data, cell_subgroups, subgroup, lis))
  }else{
    cell_subgroups = list()
    lis = list()
    ###################################################################################################################Similarity part  
    is_similar <- function(value1, value2, threshold) {return(abs(value1 - value2) <= threshold)}
    similarity_matrix <- matrix(FALSE, nrow = ncol(data), ncol = ncol(data), dimnames = list(names(data), names(data)))
    for (col1 in names(data)) {
      for (col2 in names(data)) {
        similarity <- all(mapply(is_similar, data[[col1]], data[[col2]], MoreArgs = list(thres_similarity)))
        similarity_matrix[col1, col2] <- similarity
      }
    }
    # Get upper triangle of the correlation matrix
    get_upper_tri <- function(cormat){
      cormat[lower.tri(cormat, diag = T)]<- NA
      return(cormat)
    }
    
    upper_tri <- get_upper_tri(similarity_matrix)
    x <- melt(upper_tri) %>%
      na.omit() %>%
      mutate_all(as.character)
    indice = 1
    subgroup = list()
    vec = unique(x$Var1)
    while(length(vec)>0){
      sub = x[which(x$Var1%in%vec[1]),] 
      sub = sub[which(sub$value==T),]
      if(nrow(sub)!=0){
        subgroup[[indice]] = c(vec[1], sub$Var2)
        x = x[-which(x$Var1%in%subgroup[[indice]]),]
        x = x[-which(x$Var2%in%subgroup[[indice]]),]
        vec = vec[-which(vec%in%subgroup[[indice]])]
        indice = indice + 1
      }else{
        indice = indice
        vec = vec[-1]
      }
    }
    
    if(length(subgroup)!=0){
      #Name subgroups    
      for (i in 1:length(subgroup)){ 
        names(subgroup)[i] = paste0(name, "_Subgroup.Similarity_", i)
      }
      
      lis = remove_subgroups(subgroup)
      #Groups similarity
      if(length(lis)>0){
        for (i in 1:length(subgroup)) {
          idx = which(names(subgroup[[i]])%in%lis)
          if(length(idx)>0){
            subgroup[[i]] = subgroup[[i]][-idx]  
          }
        }
      }
      lis = subgroup
      data_sub = c()
      #Take average expression of subgroups
      for(i in 1:length(subgroup)){ #Create data frame with features subgroupped
        sub = data.frame(data[,colnames(data)%in%subgroup[[i]]]) #Map features that are inside each subgroup from input (deconvolution)
        sub$average = rowMeans(sub) #Compute average of subgroup across patients 
        data_sub = data.frame(cbind(data_sub, sub$average)) #Save avg in a new data frame
        colnames(data_sub)[i] = names(subgroup)[i]
        name = colnames(data)[which(!(colnames(data)%in%subgroup[[i]]))]
        data = data[,-which(colnames(data)%in%subgroup[[i]])] #Remove from deconvolution features that are subgrouped
        if(ncol(data.frame(data))==1){
          data = as.data.frame(data)
          colnames(data)[1] = name
        }
      }
      
      rownames(data_sub) = rownames(data) #List of patients
      data_sub = data.frame(data_sub[,colnames(data_sub)%in%names(lis)])
      colnames(data_sub) = names(lis)
      
      data = cbind(data, data_sub) #Join subgroups in deconvolution file
      k = 2
    }else{
      k = 3
    }
    
    if(ncol(data) == 1){
      cell_subgroups = list()
      return(list(data, cell_subgroups, subgroup, lis))  
    }
    ###################################################################################################################Correlation part
    
    if(k==2 | k==3){
      terminate = FALSE
      iteration = 1
      while (terminate == FALSE) {
        corr_df <- correlation(data.matrix(data))
        vec = colnames(data)
        indice = 1
        subgroup = list()
        data_sub = c() 
        while(length(vec)>0){ #Keep running until no features are left
          if(vec[1] %in% corr_df$measure1){ #Check if feature still no-grouped
            tab = corr_df[corr_df$measure1 == vec[1],] #Take one feature against the others
            tab = tab[tab$r>thres_corr,] #Select features corr above the threshold = 0.75
            if(nrow(tab)!=0){ #If algorithm found features above corr
              subgroup[[indice]] = c(vec[1], tab$measure2) #Save features as subgroup
              idx = which(corr_df$measure1 %in% subgroup[[indice]])
              if(length(idx)>0){corr_df = corr_df[-idx,]} #Remove features already subgroupped 
              idy = which(corr_df$measure2 %in% subgroup[[indice]])
              if(length(idy)>0){corr_df = corr_df[-idy,]} #Remove features already subgroupped
              #corr_df = corr_df[-which(corr_df$measure1 %in% subgroup[[indice]]),] #Remove features already subgroupped
              vec = vec[-which(vec%in%subgroup[[indice]])] #Remove feature already subgroupped from vector  
              indice = indice + 1
            }else{ #Condition when there is no correlation above the threshold (features no subgroupped)
              corr_df = corr_df[-which(corr_df$measure1 == vec[1]),] #Remove variable from corr matrix to keep subgrouping the others
              if(length(which(corr_df$measure2==vec[1]))>0){corr_df = corr_df[-which(corr_df$measure2 == vec[1]),]}
              vec = vec[-1] #Remove variable from vector to keep analyzing the others 
              indice = indice #Not increase index cause no subgroup appeared
            }
          }else{ #If feature is not in corr matrix it means that there is no any significant correlation against it and other features 
            vec = vec[-1] #Remove variable from vector to keep analyzing the others
            indice = indice  #Not increase index cause no subgroup appeared
          }
        }
        
        if(length(subgroup)!=0){
          #Name subgroups
          for (i in 1:length(subgroup)){ 
            names(subgroup)[i] = paste0(name, "_Subgroup_", i, "_Iteration_", iteration)
          }
          
          #Take average expression of subgroups
          for(i in 1:length(subgroup)){ #Create data frame with features subgroupped
            sub = data.frame(data[,colnames(data)%in%subgroup[[i]]]) #Map features that are inside each subgroup from input (deconvolution)
            sub$average = rowMeans(sub) #Compute average of subgroup across patients 
            data_sub = data.frame(cbind(data_sub, sub$average)) #Save avg in a new data frame
            colnames(data_sub)[i] = names(subgroup)[i]
            name = colnames(data)[which(!(colnames(data)%in%subgroup[[i]]))]
            data = data.frame(data[,-which(colnames(data)%in%subgroup[[i]])]) #Remove from deconvolution features that are subgrouped
            if(ncol(data.frame(data))==1){
              data = as.data.frame(data)
              colnames(data)[1] = name
            }
          }
          
          rownames(data_sub) = rownames(data) #List of patients
          
          # new_average_values = colMeans(data.matrix(data_sub))
          
          if(iteration == 1){ #Save what is inside the first subgroups
            cell_subgroups = subgroup 
            data_sub = data.frame(data_sub[,colnames(data_sub)%in%names(cell_subgroups)])
            colnames(data_sub) = names(cell_subgroups)
          }
          
          # #Compare averages and test if they are above certain threshold 
          # if(iteration == 1){
          #   df = data
          # }
          #else{
          #   for (i in 1:length(subgroup)) {
          #     for (j in 1:length(idx)) {
          #       change = max(abs(average_values[idx[j]] - new_average_values[i]))
          #       if (change > thres_change) {
          #         terminate <- TRUE
          #       }
          #     }
          #   }
          # }
          # average_values = new_average_values
          
          if(ncol(data)!=0){
            data = cbind(data, data_sub)
          }else{
            data = data_sub
            terminate = TRUE
          }
          iteration = iteration + 1
        }else{
          terminate = TRUE
          #if(!is.null(tryCatch(eval(parse(text = df)), error = function(e) NULL))==F){
          #df = data
          #}
        }
        
      }
      
      if(is.null(data_sub)==TRUE){
        data = data
      }else{
        data = cbind(data, data_sub)
      }
      
      idx = which(duplicated(t(data)))
      if(length(idx)>0){
        names = colnames(data)[idx]
        data = data.frame(data[,-idx])
        if(ncol(data)==1){
         colnames(data)[1] = names 
        }
      }
    }
    
    #lis = remove_subgroups(cell
    return(list(data, cell_subgroups, subgroup, lis))
  }
  
}
```

```{r}
res = list()
groups = list()
groups_similarity = list()
for (i in 1:length(cells)) {
  x = compute_subgroups(cells[[i]], names(cells)[i])
  res = c(res, x[1])
  groups = c(groups, x[2])
  groups_similarity = c(groups_similarity, x[4])
}
names_cells = c("B", "MACROPHAGES", "M0", "M1", "M2", "MONOCYTES", "NEUTROPHILS", "NK", "NK.ACTIVATED", "NK.RESTING", "NKT", "CD4", "CD4.ACTIVATED", "CD4.RESTING", 
                        "CD8", "TREGS", "DENDRITIC", "DENDRITIC.ACTIVATED", "DENDRITIC.RESTING", "CANCER", "ENDOTHELIAL", "CAF")
names(res) = names_cells
names(groups) = names_cells
names(groups_similarity) = names_cells

#Res and Groups 
ls = remove_subgroups(groups)
for (i in 1:length(groups)) {
  idx = which(names(groups[[i]])%in%ls)
  idy = which(names(res[[i]])%in%ls)
  if(length(idx)>0){
    groups[[i]] = groups[[i]][-idx] 
    res[[i]] = res[[i]][-idy] 
  }
}

#Output deconvolution
dt = c()
for (i in 1:length(res)) {
  dt = c(dt, res[[i]])
}
dt = data.frame(dt)
rownames(dt) = rownames(deconv)

```

```{r}
png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionRESPONSE.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(dt)), clustering_method_columns = "ward.D2",width = unit(30, "cm"), height = unit(35, "cm"), column_dend_height = unit(5, "cm"), show_heatmap_legend = F)
dev.off()
```
Input data
```{r}
dataset = "Response"
TFs <- read.csv(paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_", dataset, ".csv"), row.names = 1)
```

TFs filtering
```{r}
#Remove columns with low variance (no much change across samples)
TFs = data.frame(TFs[-which(rowVars(TFs)<=summary(rowVars(TFs))[2]),])
minAbsValue <- abs(min(TFs))
TFs = TFs + minAbsValue
```

Finding modules of TFs
```{r}
projected_data = TFs
hc <- as.dendrogram(hclust(dist(t(scale(t(projected_data)))), method = "ward.D2"))
plot(hc)
rect.dendrogram(hc, h = 20,horiz=F)
clusters <- cutree(hc, h = 20)
```

TFs clustering merging
```{r}
TFs_modules = projected_data %>%
  as_tibble() %>%
  mutate("Cluster" = paste0("Cluster ", clusters)) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean)) %>%
  column_to_rownames("Cluster")

hc <- as.dendrogram(hclust(dist(t(scale(t(TFs_modules)))), method = "ward.D2"))
plot(hc)
rect.dendrogram(hc, h = 6,horiz=F)
clusters2 <- cutree(hc, h = 6)

TFs_modules_merge = TFs_modules %>%
  as_tibble() %>%
  mutate("Cluster" = paste0("Cluster ", clusters2)) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean)) %>%
  column_to_rownames("Cluster")

png(paste0(getwd(),"/Figures/Heatmaps/New2/TFs_modules_RESPONSE.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(t(TFs_modules_merge))), clustering_method_columns = "ward.D2", width = unit(30, "cm"), height = unit(20, "cm"), column_dend_height = unit(10, "cm"))
dev.off()
```

Correlating deconvolution with TFs activity
```{r}
TFs_modules_merge = TFs_modules_merge[,colnames(TFs_modules_merge)%in%rownames(dt)]
moduleTraitCor = cor(t(TFs_modules_merge), dt, use = "p")
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples)

textMatrix =  paste(signif(moduleTraitCor, 2), "\n(",
                  signif(moduleTraitPvalue, 1), ")", sep = "")
dim(textMatrix) = dim(moduleTraitCor)
  
idx = which(moduleTraitPvalue>0.05)
for (i in idx) {
  textMatrix[i] = NA
}

d <- dist(t(moduleTraitCor), method = "euclidean")
hc1 <- hclust(d, method = "ward.D2" )
vec = hc1[["order"]]
  
###Figure module-trait relationship
png(paste0(getwd(),"/Figures/Heatmaps/New2/Module_trait_relationships_", dataset, ".png"), width = 3500, height = 1500, res=150)
par(mar = c(20, 10, 4, 4)) #bottom, left, top, right
labeledHeatmap(Matrix = moduleTraitCor[,vec],
               xLabels = names(dt[,vec]),
               yLabels = rownames(TFs_modules_merge),
               ySymbols = rownames(TFs_modules_merge),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               textMatrix = textMatrix[,vec],
               setStdMargins = FALSE,
               cex.text = 0.8,
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
dev.off()
```

Figure dendogram cell types based on TFs activity 
```{r}
hc = as.dendrogram(hc1)
png(paste0(getwd(),"/Figures/Heatmaps/New2/Dendogram_Subgroups_cells_", dataset, ".png"), width = 2500, height = 2500, res=150)
par(mar = c(5, 5, 4, 30)) #bottom, left, top, right
plot(hc, horiz= T)
rect.dendrogram(hc, h=0.5,horiz=TRUE)
dev.off()

clusters3 <- cutree(hc, h = 0.5)

png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionRESPONSE_TFs.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(dt)), cluster_rows = hc, clustering_method_columns = "ward.D2",width = unit(30, "cm"), height = unit(35, "cm"), column_dend_height = unit(5, "cm"), show_heatmap_legend = F)
dev.off()
```

Merging deconvolution clusters
```{r}
deconv_df = dt %>%
  t() %>%
  as_tibble() %>%
  mutate("Cluster" = paste0("Cluster_", clusters3)) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean)) %>%
  column_to_rownames("Cluster")

png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionRESPONSE_Clusters.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(t(deconv_df))), clustering_method_columns = "ward.D2",width = unit(30, "cm"), height = unit(35, "cm"), column_dend_height = unit(5, "cm"), show_heatmap_legend = F)
dev.off()
```

Clustering patients early stage LP and Vanderbilt
```{r}
dataset = "LungPredict"
colData_LP <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = 1)
data = t(deconv_df)
LP = data[rownames(data)%in%rownames(colData_LP),]
colData_LP = colData_LP[rownames(colData_LP)%in%rownames(LP),]

hc1 = as.dendrogram(hclust(dist(scale(LP)), method = "ward.D2"))
plot(hc1)
rect.dendrogram(hc1, k=2,horiz=F)
clusters <- cutree(hc1, k=2)
colData_LP$cluster = NULL
colData_LP$cluster = clusters

response <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_Response.csv"), row.names = 1)
response = response[rownames(response)%in%rownames(colData_LP),]
response_dt = dt[rownames(dt)%in%rownames(response),]
response = response[-which(response$response=="No data"),]
LP = LP[rownames(LP)%in%rownames(response),]
colData_LP = colData_LP[rownames(colData_LP)%in%rownames(response),]

random_forest <- function(data, target, k_features) {
  # Step 1: Random Forest Feature Selection
  target = as.factor(target)
  # Step 2: Random Forest Classification
  rf_classifier <- randomForest(target ~ ., data = data)
  rf_importance <- importance(rf_classifier)
  rf_importance <- rf_importance[order(rf_importance, decreasing = TRUE), ]
  rf_selected_features <- data[, names(rf_importance[order(rf_importance, decreasing = TRUE)][1:k_features])]
  rf_importance = data.frame(rf_importance)
  colnames(rf_importance)[1] = "Importance"
  return(list(rf_selected_features, rf_importance))
}

res = random_forest(data.frame(LP), colData_LP$cluster, 10)

ggplot(res[[2]], aes(x = reorder(rownames(res[[2]]), -Importance), y = Importance)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(x = "Features", y = "Importance") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

hclu = hclust(dist(t(scale(res[[1]]))), method = "ward.D2")
vec = hclu[["order"]]

colData_LP$response = response$response
png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionRESPONSE_FS_JOINED_TFs.png"), width = 6000, height = 4500, res=250)
ha <- HeatmapAnnotation(Response = colData_LP$response, Cluster = colData_LP$cluster, col = list(Response = c("Responders" = "green", "Non responders"= "red"), Cluster = c("1" = "green", "2" = "purple")))
Heatmap(t(scale(res[[1]][,vec])), cluster_rows = F,  clustering_method_columns = "ward.D2", top_annotation = ha, width = unit(30, "cm"), height = unit(20, "cm"), column_dend_height = unit(10, "cm"), row_dend_width = unit(10, "cm"))
dev.off()
```

Save cell clusters
```{r}
data = dt %>%
  t() %>%
  as_tibble() %>%
  mutate("Cluster" = clusters3) %>%
  as.data.frame()
rownames(data) = colnames(dt)
niches = list()
for (i in 1:nrow(deconv_df)) {
  niches[[i]] = rownames(data)[which(data$Cluster==i)]
}
```

Vanderbilt validation
```{r}
dataset = "Vanderbilt"
data = t(deconv_df)
colData_Van <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = 1)
Van = data[rownames(data)%in%rownames(colData_Van),]
Van = Van[,colnames(Van)%in%colnames(res[[1]])]
colData_Van = colData_Van[rownames(colData_Van)%in%rownames(Van),]

names = colnames(res[[1]][,vec])

png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionVan_FS_JOINED_TFs.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(Van[, names])), cluster_rows = F, clustering_method_columns = "ward.D2", width = unit(30, "cm"), height = unit(20, "cm"), column_dend_height = unit(10, "cm"), row_dend_width = unit(10, "cm"))
dev.off()
```

