---
title: "singleCell_pseudoBulk"
author: "Marcelo Hurtado"
date: "2023-07-11"
output: html_document
---

```{r}
library(ExperimentHub)
library(Seurat)
library(DESeq2)
library(tidyverse)
source(paste0(getwd(),"/environment_set.R"))
libraries_set()
```

Load data 
```{r}
NK = readRDS("nk2.rds")
macrophages = readRDS("macrophages.rds")
levels(Idents(NK))
levels(Idents(macrophages))
```
```{r}
DimPlot(NK, reduction="umap")
ElbowPlot(NK) #determine dimensionality of data
NK<- FindNeighbors(NK, dims = 1:15)
NK<- FindClusters(NK, algorithm= 1, resolution = 0.15, verbose = T, graph.name = "RNA_snn")
NK<- RunUMAP(NK, dims = 1:15)
DimPlot(NK, reduction="umap", label = T, pt.size = 0.5) + 
  NoLegend() + ggtitle('NK cells TF activity')
```
```{r}
markers = FindAllMarkers(NK,
               logfc.threshold = 0.25, #min logfc 
               min.pct = 0.1, #genes that are detected on 50% frequency across clusters
               only.pos = T,
               test.use = 'wilcox',
               slot = 'counts')
head(markers[which(markers$cluster==0),], n =5)
head(markers[which(markers$cluster==1),], n =5)
head(markers[which(markers$cluster==2),], n =5)
```
```{r}
DimPlot(macrophages, reduction="umap")
ElbowPlot(macrophages) #determine dimensionality of data
macrophages<- FindNeighbors(macrophages, dims = 1:15)
macrophages<- FindClusters(macrophages, algorithm= 1, resolution = 0.15, verbose = T, graph.name = "RNA_snn")
macrophages<- RunUMAP(macrophages, dims = 1:15)
DimPlot(macrophages, reduction="umap", label = T, pt.size = 0.5) + 
  NoLegend() + ggtitle('Macrophages cells TF activity')
```

```{r}
markers = FindAllMarkers(macrophages,
               logfc.threshold = 0.25, #min logfc 
               min.pct = 0.1, #genes that are detected on 50% frequency across clusters
               only.pos = T,
               test.use = 'wilcox',
               slot = 'counts')
head(markers[which(markers$cluster==0),], n =20)
head(markers[which(markers$cluster==1),], n =20)
```

Pseudo-bulk workflow
```{r}
# 1. counts matrix - sample level
View(macrophages@meta.data) # Acquiring necessary metrics for aggregation across cells in a sample
DefaultAssay(NK)
NK$samples <- paste0("NK.", Idents(NK))
# counts aggregate to sample level
cts <- AggregateExpression(NK, 
                    group.by = c("samples", "sample"),
                    assays = 'RNA',
                    slot = "counts",
                    return.seurat = FALSE)

macrophages$samples <- paste0("Macrophages.", Idents(macrophages))
# counts aggregate to sample level
cts <- AggregateExpression(macrophages, 
                    group.by = c("samples", "sample"),
                    assays = 'RNA',
                    slot = "counts",
                    return.seurat = FALSE)

cts <- cts$RNA

cts.t <- t(cts) # transpose
cts.t <- as.data.frame(cts.t)

# get values where to split
splitRows <- gsub('_.*', '', rownames(cts.t))


# split data.frame
cts.split <- split.data.frame(cts.t,
                 f = factor(splitRows))

# fix colnames and transpose

cts.split.modified <- lapply(cts.split, function(x){
  rownames(x) <- gsub('.*_(.*)', '\\1', rownames(x))
  t(x)
  
})

dt1 = cts.split.modified$NK.Cluster1
colnames(dt1) = paste0(colnames(dt1), "_version1_nk")
dt2 = cts.split.modified$NK.Cluster2
colnames(dt2) = paste0(colnames(dt2), "_version2_nk")
dt3 = cts.split.modified$NK.Cluster3
colnames(dt3) = paste0(colnames(dt3), "_version3_nk")

dt1.2 = cts.split.modified2$Macrophages.Cluster1
colnames(dt1.2) = paste0(colnames(dt1.2), "_version1_macro")
dt2.2 = cts.split.modified2$Macrophages.Cluster2
colnames(dt2.2) = paste0(colnames(dt2.2), "_version2_macro")
dt3.2 = cts.split.modified2$Macrophages.Cluster3
colnames(dt3.2) = paste0(colnames(dt3.2), "_version3_macro")


data = cbind(dt1, dt2, dt3, dt1.2, dt2.2, dt3.2)
colnames(data)
hc <- as.dendrogram(hclust(dist(scale(t(data))), method = "ward.D"))
png(paste0(getwd(),"/Figures/Heatmaps/New2/TFs_clusters_EARLYSTAGE.png"), width = 7500, height = 4500, res=250)
plot(hc)
rect.dendrogram(hc, k = 2,horiz=F)
dev.off()
```

```{r}
cts.top = cts.t[,order(colVars(as.matrix(cts.t)), decreasing=T)[1:50]]
png(paste0(getwd(),"/SingleCell_aggregation_NK.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(cts.top)), cluster_rows = F,  clustering_method_columns = "ward.D2", width = unit(30, "cm"), height = unit(20, "cm"), column_dend_height = unit(10, "cm"), row_dend_width = unit(10, "cm"))
dev.off()
```
```{r}
hc <- as.dendrogram(hclust(dist(scale(cts.top2)), method = "ward.D2"))
png(paste0(getwd(),"/Figures/Heatmaps/New2/TFs_clusters_EARLYSTAGE.png"), width = 7500, height = 4500, res=250)
plot(hc)
rect.dendrogram(hc, k = 2,horiz=F)
dev.off()
clusters <- cutree(hc,  k = 2)
colData$cluster = clusters
```

Run msViper between conditions
```{r}

dorothea2viper_regulons <- function(df) {
    regulon_list <- split(df, df$tf)
    viper_regulons <- lapply(regulon_list, function(regulon) {
      tfmode <- stats::setNames(regulon$mor, regulon$target)
      list(tfmode = tfmode, likelihood = rep(1, length(tfmode)))
    })
    
    return(viper_regulons)
  }
  
  data("dorothea_hs", package = "dorothea")
  regulons <- dorothea_hs %>%
    filter(confidence %in% c("A", "B", "C"))
  regu <- dorothea2viper_regulons(regulons)
  cts = as.data.frame(cts)

  # Generating test and ref data
  test_i <- which(colData$cluster == "2")
  ref_i <- which(colData$cluster == "1")
  
  mat_test <- as.matrix(cts[,test_i])
  mat_ref <- as.matrix(cts[,ref_i])
  
  # Generating NULL model (test, reference)
  dnull <- ttestNull(mat_test, mat_ref, per=1000)
  
  # Generating signature
  signature <- rowTtest(mat_test, mat_ref)
  signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))
  signature <- na.omit(signature)
  signature <- signature[,1]
  
  # Running msVIPER
  mra <- msviper(signature, regu, dnull, verbose = FALSE)

  # Plot DiffActive TFs
  png(paste0(getwd(),"Single_cell_DifferentialActive_TFs.png"), width = 1000, height = 800, res=100)
  print(plot(mra, cex=1, include = c("expression","activity")))
  dev.off()
  

```


