---
title: "Subgroups"
author: "Marcelo Hurtado"
date: "2023-02-08"
output: html_document
---

Datasets
```{r}
dataset = "LungPredict"
dataset = "VanIP"
dataset = "Vanderbilt"
dataset = "Response"
dataset = "Melanoma"
dataset = "Immucan"
dataset = "TCGA"
dataset = "Liu"
dataset = "Gide"
```

```{r}
deconv <- read.csv(paste0(getwd(),"/Output/Deconvolution/Deconvolution_afterFS_", dataset, ".txt"), row.names = 1)
#Deconvolution subgroups
Bcells = readRDS(paste0(getwd(),"/Output/Subgroups/B_",dataset,"_subgroups.rds"), refhook = NULL)
CD4 = readRDS(paste0(getwd(),"/Output/Subgroups/CD4_",dataset,"_subgroups.rds"), refhook = NULL)
CD8 = readRDS(paste0(getwd(),"/Output/Subgroups/CD8_",dataset,"_subgroups.rds"), refhook = NULL)
M1 = readRDS(paste0(getwd(),"/Output/Subgroups/M1_",dataset,"_subgroups.rds"), refhook = NULL)
M2 = readRDS(paste0(getwd(),"/Output/Subgroups/M2_",dataset,"_subgroups.rds"), refhook = NULL)
M0 = readRDS(paste0(getwd(),"/Output/Subgroups/M0_",dataset,"_subgroups.rds"), refhook = NULL)
Monocytes = readRDS(paste0(getwd(),"/Output/Subgroups/Mono_",dataset,"_subgroups.rds"), refhook = NULL)
NK = readRDS(paste0(getwd(),"/Output/Subgroups/NK_",dataset,"_subgroups.rds"), refhook = NULL)
Cancer = readRDS(paste0(getwd(),"/Output/Subgroups/Cancer_",dataset,"_subgroups.rds"), refhook = NULL)
CAF = readRDS(paste0(getwd(),"/Output/Subgroups/CAF_",dataset,"_subgroups.rds"), refhook = NULL)
Macrophages = readRDS(paste0(getwd(),"/Output/Subgroups/Macrophages_",dataset,"_subgroups.rds"), refhook = NULL)
Dendritic = readRDS(paste0(getwd(),"/Output/Subgroups/Dendritic_",dataset,"_subgroups.rds"), refhook = NULL)
Neutrophils = readRDS(paste0(getwd(),"/Output/Subgroups/Neutrophils_",dataset,"_subgroups.rds"), refhook = NULL)
Endothelial = readRDS(paste0(getwd(),"/Output/Subgroups/Endothelial_",dataset,"_subgroups.rds"), refhook = NULL)
#TFs modules
TFs = readRDS(paste0(getwd(),"/Output/WGCNA/TFs_modules_",dataset), refhook = NULL)

#Immune niches
Features = readRDS(paste0(getwd(),"/Output/DataIntegration/Immune_niches_",dataset), refhook = NULL)

deconv <- read.csv(paste0(getwd(),"/Output/Deconvolution/Deconvolution_afterFS_", dataset, ".txt"), row.names = 1)

```

```{r}
celltypes = list(Bcells, CD4, CD8, M1, M2, M0, Monocytes, NK, Cancer, CAF, Macrophages, Dendritic, Neutrophils)
for (pos in 1:length(celltypes)){
  lis = c()
  for (i in 1:length(celltypes[[pos]])) {
    x = c()
    for (j in 1:length(celltypes[[pos]][[i]])) {
      x =  c(x,str_split(celltypes[[pos]][[i]], "_")[[j]][1])
    }
    if(length(unique(x)) == 1){
      lis = c(lis, names(celltypes[[pos]])[[i]])
    }
  }
  if(length(lis)>0){
    celltypes[[pos]] = celltypes[[pos]][-which(names(celltypes[[pos]])%in%lis)]
  }
  else{
    celltypes[[pos]] = celltypes[[pos]]
  }
}

names = c()
for (i in 1:length(celltypes)) {
  names = c(names,unlist(names(celltypes[[i]])))
}

deconv = deconv[,colnames(deconv)%in%names]
write.csv(deconv, paste0(getwd(),"/Output/Deconvolution/Deconvolution_afterFS_", dataset, ".txt"))
```


Removing subgroups
```{r}
###############################################Bcells
# B_LungPredict_Subgroup_2
# B_LungPredict_Subgroup_6
###############################################Cancer
# Cancer_LungPredict_Subgroup_2
###############################################CD4
# CD4_LungPredict_Subgroup_7
# CD4_LungPredict_Subgroup_9
###############################################CD8
# CD8_LungPredict_Subgroup_5
###############################################M0
# M0_LungPredict_Subgroup_1
###############################################M1
# M1_LungPredict_Subgroup_2
##############################################Monocytes
# Mono_LungPredict_Subgroup_5
# Mono_LungPredict_Subgroup_7
#############################################NK cells
# NK_LungPredict_Subgroup_5
# NK_LungPredict_Subgroup_1_7
# NK_LungPredict_Subgroup_6
############################################Dendritic
# Dendritic_LungPredict_Subgroup_5
# Dendritic_LungPredict_Subgroup_6
# Dendritic_LungPredict_Subgroup_3
# Dendritic_LungPredict_Subgroup_2
#############################################Endothelial
# Endothelial_LungPredict_Subgroup_2

vec = c("B_LungPredict_Subgroup_2", "B_LungPredict_Subgroup_6", "Cancer_LungPredict_Subgroup_2", "CD4_LungPredict_Subgroup_7", "CD4_LungPredict_Subgroup_9", "CD8_LungPredict_Subgroup_5", "M0_LungPredict_Subgroup_1", "M1_LungPredict_Subgroup_2", "Mono_LungPredict_Subgroup_5", "Mono_LungPredict_Subgroup_7",  "NK_LungPredict_Subgroup_5", "NK_LungPredict_Subgroup_6", "NK_LungPredict_Subgroup_7", "Dendritic_LungPredict_Subgroup_5", "Dendritic_LungPredict_Subgroup_6", "Dendritic_LungPredict_Subgroup_3", "Endothelial_LungPredict_Subgroup_2")


```

