---
title: "TFsClustering"
author: "Marcelo Hurtado"
date: "2023-06-14"
output: html_document
---

```{r}
dataset = "LPVan"
TFs <- read.csv(paste0(getwd(),"/Output/TFs/VIPER/TFs_scores_all_", dataset, ".csv"), row.names = 1)
```

```{r}
#Remove columns with low variance (no much change across samples)
TFs = data.frame(TFs[-which(rowVars(TFs)<=summary(rowVars(TFs))[2]),])
minAbsValue <- abs(min(TFs))
TFs = TFs + minAbsValue
```

```{r}
data = t(TFs)
# Step 1: Compute the covariance or correlation matrix
cov_matrix <- cov(data)  # Or use cor(data) for correlation matrix

# Step 2: Perform eigenvalue decomposition
eigen_decomp <- eigen(cov_matrix)

# Step 3: Sort eigenvectors by eigenvalues in descending order
sorted_eigenvec <- eigen_decomp$vectors[, order(eigen_decomp$values, decreasing = TRUE)]
data = data[,order(eigen_decomp$values, decreasing = TRUE)]
colnames(sorted_eigenvec) = colnames(data)
rownames(sorted_eigenvec) = colnames(data)

# Step 4: Select a subset of top eigenvectors
total_variance <- sum(eigen_decomp$values)
explained_variance <- cumsum(eigen_decomp$values) / total_variance

# Select eigenvectors that explain a significant portion of the variance
threshold <- 0.9
selected_eigenvec <- sorted_eigenvec[, explained_variance >= threshold]

# Step 5: Project original data onto selected eigenvectors
projected_data <- data %*% selected_eigenvec

# Step 6: Perform hierarchical clustering on the projected data
projected_data = TFs
hc <- as.dendrogram(hclust(dist(t(scale(t(projected_data)))), method = "ward.D2"))
plot(hc)
rect.dendrogram(hc, h = 20,horiz=F)

clusters <- cutree(hc, h = 20)

# Print the clusters
print(clusters)

```

```{r}
TFs_modules = projected_data %>%
  as_tibble() %>%
  mutate("Cluster" = paste0("Cluster ", clusters)) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean)) %>%
  column_to_rownames("Cluster")

hc <- as.dendrogram(hclust(dist(t(scale(t(TFs_modules)))), method = "ward.D2"))
plot(hc)
rect.dendrogram(hc, h = 10,horiz=F)
clusters2 <- cutree(hc, h = 10)

TFs_modules_merge = TFs_modules %>%
  as_tibble() %>%
  mutate("Cluster" = paste0("Cluster ", clusters2)) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean)) %>%
  column_to_rownames("Cluster")
```

```{r}
png(paste0(getwd(),"/Figures/Heatmaps/New2/TFs_modules.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(t(TFs_modules_merge))), clustering_method_columns = "ward.D2", width = unit(30, "cm"), height = unit(20, "cm"), column_dend_height = unit(10, "cm"))
dev.off()
```

```{r}
TFs_modules_merge = TFs_modules_merge[,colnames(TFs_modules_merge)%in%rownames(dt)]
moduleTraitCor = cor(t(TFs_modules_merge), dt, use = "p")
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples)

textMatrix =  paste(signif(moduleTraitCor, 2), "\n(",
                  signif(moduleTraitPvalue, 1), ")", sep = "")
dim(textMatrix) = dim(moduleTraitCor)
  
idx = which(moduleTraitPvalue>0.05)
for (i in idx) {
  textMatrix[i] = NA
}

d <- dist(t(moduleTraitCor), method = "euclidean")
hc1 <- hclust(d, method = "ward.D2" )
vec = hc1[["order"]]
  
###Figure module-trait relationship
png(paste0(getwd(),"/Figures/Heatmaps/New2/Module_trait_relationships_", dataset, ".png"), width = 3500, height = 1500, res=150)
par(mar = c(20, 10, 4, 4)) #bottom, left, top, right
labeledHeatmap(Matrix = moduleTraitCor[,vec],
               xLabels = names(dt[,vec]),
               yLabels = rownames(TFs_modules_merge),
               ySymbols = rownames(TFs_modules_merge),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               textMatrix = textMatrix[,vec],
               setStdMargins = FALSE,
               cex.text = 0.8,
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
dev.off()
```
```{r}
hc = as.dendrogram(hc1)
###Figure dendogram cell types based on TFs activity 
png(paste0(getwd(),"/Figures/Heatmaps/New2/Dendogram_Subgroups_cells_", dataset, ".png"), width = 2500, height = 2500, res=150)
par(mar = c(5, 5, 4, 30)) #bottom, left, top, right
plot(hc, horiz= T)
rect.dendrogram(hc, h=0.8,horiz=TRUE)
dev.off()

clusters3 <- cutree(hc, h = 0.8)
```

```{r}
png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionLP_TFs.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(dt)), cluster_rows = hc, clustering_method_columns = "ward.D2",width = unit(30, "cm"), height = unit(35, "cm"), column_dend_height = unit(5, "cm"), show_heatmap_legend = F)
dev.off()
```
```{r}
deconv_df = dt %>%
  t() %>%
  as_tibble() %>%
  mutate("Cluster" = paste0("Cluster ", clusters3)) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean)) %>%
  column_to_rownames("Cluster")
```

```{r}
png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionLP_Clusters.png"), width = 6000, height = 4500, res=250)
Heatmap(t(scale(t(deconv_df))), clustering_method_columns = "ward.D2",width = unit(30, "cm"), height = unit(35, "cm"), column_dend_height = unit(5, "cm"), show_heatmap_legend = F)
dev.off()
```

```{r}
dataset = "LungPredict"
colData_LP <- read.csv(paste0(getwd(),"/Input/ClinicalData/ClinicalData_", dataset, ".csv"), row.names = 1)
data = t(deconv_df)
LP = data[rownames(data)%in%rownames(colData_LP),]
colData_LP = colData_LP[rownames(colData_LP)%in%rownames(LP),]
hc1 = as.dendrogram(hclust(dist(scale(LP)), method = "ward.D2"))
plot(hc1)
rect.dendrogram(hc1, k=2,horiz=F)
clusters <- cutree(hc1, k=2)
colData_LP$cluster = NULL
colData_LP$cluster = clusters

random_forest <- function(data, target, k_features) {
  # data = LP
  # target = colData_LP$cluster
  # Step 1: Random Forest Feature Selection
  target = as.factor(target)
  # Step 2: Random Forest Classification
  rf_classifier <- randomForest(target ~ ., data = data)
  rf_importance <- importance(rf_classifier)
  rf_importance <- rf_importance[order(rf_importance, decreasing = TRUE), ]
  rf_selected_features <- data[, names(rf_importance[order(rf_importance, decreasing = TRUE)][1:k_features])]
  rf_importance = data.frame(rf_importance)
  colnames(rf_importance)[1] = "Importance"
  return(list(rf_selected_features, rf_importance))
}

res = random_forest(data.frame(LP), colData_LP$cluster, 10)

png(paste0(getwd(),"/Figures/Heatmaps/New2/DeconvolutionLP_FS_JOINED_TFs.png"), width = 6000, height = 4500, res=250)
ha <- HeatmapAnnotation(Cluster = colData_LP$cluster, col = list(Cluster = c("1" = "green", "2" = "purple")))
Heatmap(t(scale(res[[1]])),  clustering_method_columns = "ward.D2", top_annotation = ha, width = unit(30, "cm"), height = unit(20, "cm"), column_dend_height = unit(10, "cm"), row_dend_width = unit(10, "cm"))
dev.off()
```

